server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ding?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: root

mybatis:
  configuration:
    #开启下划线与驼峰映射
    map-underscore-to-camel-case: true
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 给实体类起别名
  type-aliases-package: ding.pojo,ding.dto
  # 指定映射文件目录
  mapper-locations: classpath:mapper/*.xml